apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-http-server
  template:
    metadata:
      labels:
        app: rust-http-server
    spec:
      containers:
      - name: rust-http-server
        image: dwaltonacr.azurecr.io/http-server:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rust-http-service
spec:
  selector:
    app: rust-http-server
  ports:
    - port: 80
      targetPort: 8080